apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frontend-team
  namespace: argocd
spec:
  description: Project for frontend team apps
  sourceRepos:
    - https://github.com/Uday-Kumar033/ArgoCD_Tutorial.git
  destinations:
    - namespace: frontend
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
    - name: frontend-admins
      description: Admins for frontend team
      policies:
        - p, proj:frontend-team:frontend-admins, applications, *, frontend-team/*, allow

